name: publish

on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string
      package:
        required: true
        type: string
    secrets:
      github-token:
        required: true
      npm-publish-token:
        required: true
      token:
        required: true

jobs:
  publish:
    name: bump version and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current git repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.token }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install yarn dependencies
        run: yarn install --immutable
      - name: Build package
        run: yarn workspace ${{ inputs.package }} build
      - name: Load package version
        id: load_version
        run: |
          if [ "$GITHUB_EVENT_NAME" = 'workflow_dispatch' ]
          then
            VERSION="${{ github.event.inputs.version }}"
          else
            if [ "$GITHUB_EVENT_NAME" = 'release' ]
            then
              TAG_NAME="${{ github.event.release.tag_name }}"
            else
              TAG_NAME="${{ github.ref }}"
            fi
            CLEAN_TAG=${TAG_NAME##*/}
            VERSION=${CLEAN_TAG//v}
          fi
          echo "::set-output name=version::$VERSION"
      - name: Update package.json version to ${{ steps.load_version.outputs.version }}
        uses: mikefarah/yq@v4.24.5
        with:
          cmd: |
            yq eval '.version = "${{ steps.load_version.outputs.version }}"' -i ${{ inputs.directory }}/package.json -j
      - name: Commit new package.json version
        run: |
          git config --global user.email "nic.s.pearson@gmail.com"
          git config --global user.name "Nicbotic"
          git add ${{ inputs.directory }}/package.json
          git commit -m "chore(): release ${{ inputs.package }}@${{ steps.load_version.outputs.version }} [skip-ci]"
      - name: Push changes to current git repository
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: main
          force: true
          github_token: ${{ secrets.github-token }}
      - name: Publish the package
        run: |
          cd ${{ inputs.directory }}
          npm --no-git-tag-version version $RELEASE_VERSION
          npm config set registry https://registry.npmjs.org
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm-publish-token }}
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
